{
 "title": "Hadoop监控",
 "description": "依托于自己开发的指标采集端点完成的Hadoop生态监控",
 "tags": [ "Meepo" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namenode",
    "query": {
     "query": "query_result((NameNode_isActive==1) / on(serverip)(NameNode_isActive==1) )"
    }
   },
   { "name": "cluster", "label": "集群名称", "query": "物联网" },
   { "name": "interval", "label": "采样间隔", "query": "2m,5m,10m,15m,30m" },
   {
    "name": "resourcemanager",
    "query": {
     "query": "query_result((ResourceManager_isActive ==1) / on(serverip)(ResourceManager_isActive ==1) )"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "HDFS概览-$cluster" }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_CapacityUsed{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "已用空间"
    },
    {
     "expr": "NameNode_CapacityTotal{serverip=~\"$namenode\",clusters=~\"$cluster\"} - NameNode_CapacityUsed{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "剩余空间"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_isActive{clusters=~\"$cluster\"}==1",
     "legendFormat": "Active {{serverip}}"
    },
    {
     "expr": "NameNode_isActive{clusters=~\"$cluster\"}==0",
     "legendFormat": "Standby {{serverip}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_LastCheckpointTime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "检查点"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_LastHATransitionTime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "HA切换"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_NumLiveDataNodes {serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "存活DN"
    },
    {
     "expr": "NameNode_NumDeadDataNodes{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "宕机DN"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_VolumeFailuresTotal{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "坏盘数量"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_NumActiveClients{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "活跃连接数"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_CapacityTotal{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "总存储"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_CapacityUsed{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "已使用"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_CapacityUsedNonDFS{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "非HDFS使用"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(NameNode_LogWarn{serverip=~\"$namenode\",clusters=~\"$cluster\"}[1h])",
     "legendFormat": "Warn日志[1h]"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(NameNode_LogError{serverip=~\"$namenode\",clusters=~\"$cluster\"}[1h])",
     "legendFormat": "Error日志[1h]"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(NameNode_LogFatal{serverip=~\"$namenode\",clusters=~\"$cluster\"}[1h])",
     "legendFormat": "Fatal日志[1h]"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_heapMemoryUsageUsed{serverip=~\"$namenode\",clusters=~\"$cluster\"}/NameNode_heapMemoryUsageMax{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "JVM使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_Uptime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "运行时长"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_BlocksTotal{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "Block数"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_FilesTotal {serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "文件数"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-NameNode_FreePhysicalMemorySize{serverip=~\"$namenode\",clusters=~\"$cluster\"}/NameNode_TotalPhysicalMemorySize{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_SystemLoadAverage{serverip=~\"$namenode\",clusters=~\"$cluster\"}/NameNode_AvailableProcessors{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "负载程度"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_OpenFileDescriptorCount{serverip=~\"$namenode\",clusters=~\"$cluster\"}/NameNode_MaxFileDescriptorCount{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "FD Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_NumDecommissioningDataNodes{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "下线DN"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_RpcQueueTimeAvgTime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC请求延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_RpcProcessingTimeAvgTime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC操作延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_CorruptBlocks{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "损坏块"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_PendingDeletionBlocks{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "待删除块"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_UnderReplicatedBlocks{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "副本不足块"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_MissingBlocks{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "缺失块"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_ExcessBlocks{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "多余块"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NameNode_StaleDataNodes{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "过期DN"
    }
   ]
  },
  {
   "title": "HDFS数据增长趋势(test)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(NameNode_CapacityUsed{serverip=~\"$namenode\",clusters=~\"$cluster\"}[10m])",
     "legendFormat": "HDFS数据净增长趋势"
    }
   ]
  },
  {
   "title": "HDFS存储使用趋势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "NameNode_CapacityUsed{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "HDFS已用容量"
    },
    {
     "expr": "NameNode_CapacityTotal{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "HDFS总容量"
    }
   ]
  },
  {
   "title": "RPC延迟趋势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "NameNode_RpcProcessingTimeAvgTime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC操作延迟"
    },
    {
     "expr": "NameNode_RpcQueueTimeAvgTime{serverip=~\"$namenode\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC请求延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "YARN概览-$cluster" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_isActive{clusters=~\"$cluster\"}==1",
     "legendFormat": "Active {{serverip}}"
    },
    {
     "expr": "ResourceManager_isActive{clusters=~\"$cluster\"}==0",
     "legendFormat": "Standby {{serverip}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ResourceManager_RpcProcessingTimeAvgTime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC操作延迟"
    },
    {
     "expr": "ResourceManager_RpcQueueTimeAvgTime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC请求延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_running_0{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RUNNING_0"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_AllocatedMB{serverip=~\"$resourcemanager\"}/(ResourceManager_AllocatedMB{serverip=~\"$resourcemanager\"}+ResourceManager_AvailableMB{serverip=~\"$resourcemanager\"}+ResourceManager_ReservedMB{serverip=~\"$resourcemanager\"})",
     "legendFormat": "Yarn内存使用率"
    },
    {
     "expr": "ResourceManager_AllocatedVCores{serverip=~\"$resourcemanager\"}/(ResourceManager_AllocatedVCores{serverip=~\"$resourcemanager\"}+ResourceManager_AvailableVCores{serverip=~\"$resourcemanager\"}+ResourceManager_ReservedVCores{serverip=~\"$resourcemanager\"})",
     "legendFormat": "Yarn内核使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_Uptime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "运行时长"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_heapMemoryUsageUsed{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}/ResourceManager_heapMemoryUsageMax{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "JVM使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-ResourceManager_FreePhysicalMemorySize{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}/ResourceManager_TotalPhysicalMemorySize{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_SystemLoadAverage{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}/ResourceManager_AvailableProcessors{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "负载程度"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_running_60{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RUNNING_60"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_RpcProcessingTimeAvgTime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC操作延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_RpcQueueTimeAvgTime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RPC请求延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_AMLaunchDelayAvgTime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "AM启动延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_AMRegisterDelayAvgTime{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "AM注册延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_running_300{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}+ResourceManager_running_1440{serverip=~\"$resourcemanager\",clusters=~\"$cluster\"}",
     "legendFormat": "RUNNING_300"
    }
   ]
  },
  {
   "title": "节点状态",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ResourceManager_NumActiveNms{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ResourceManager_NumLostNMs{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Lost"
    },
    {
     "expr": "ResourceManager_NumUnhealthyNMs{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "ResourceManager_NumDecommissioningNMs{serverip=~\"$resourcemanager\"}+ResourceManager_NumDecommissionedNMs{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Decommission"
    },
    {
     "expr": "ResourceManager_NumRebootedNMs{serverip=~\"$resourcemanager\"}+ResourceManager_NumShutdownNMs{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ResourceManager_AllocatedMB{serverip=~\"$resourcemanager\"}/(ResourceManager_AllocatedMB{serverip=~\"$resourcemanager\"}+ResourceManager_AvailableMB{serverip=~\"$resourcemanager\"}+ResourceManager_ReservedMB{serverip=~\"$resourcemanager\"})",
     "legendFormat": "Yarn内存使用率"
    },
    {
     "expr": "ResourceManager_AllocatedVCores{serverip=~\"$resourcemanager\"}/(ResourceManager_AllocatedVCores{serverip=~\"$resourcemanager\"}+ResourceManager_AvailableVCores{serverip=~\"$resourcemanager\"}+ResourceManager_ReservedVCores{serverip=~\"$resourcemanager\"})",
     "legendFormat": "Yarn内核使用率"
    },
    {
     "expr": "ResourceManager_AppsRunning{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Running任务数"
    },
    {
     "expr": "ResourceManager_AppsPending{serverip=~\"$resourcemanager\"}",
     "legendFormat": "Pending任务数"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "DataNode监控指标" }
   ]
  },
  {
   "title": "组件性能",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(DataNode_RpcProcessingTimeNumOps{clusters=~\"$cluster\"}[$interval])",
     "legendFormat": "RPC请求增量"
    },
    {
     "expr": "DataNode_RpcProcessingTimeAvgTime{clusters=~\"$cluster\"}",
     "legendFormat": "RPC请求延迟"
    },
    {
     "expr": "DataNode_CapacityUsed{clusters=~\"$cluster\"}/DataNode_CapacityTotal{clusters=~\"$cluster\"}",
     "legendFormat": "存储使用率"
    },
    {
     "expr": "DataNode_heapMemoryUsageUsed{clusters=~\"$cluster\"}/DataNode_heapMemoryUsageMax{clusters=~\"$cluster\"}",
     "legendFormat": "JVM使用率"
    },
    {
     "expr": "DataNode_VolumeFailures{clusters=~\"$cluster\"}",
     "legendFormat": "不可用存储"
    },
    {
     "expr": "DataNode_ReadBlockOpAvgTime{clusters=~\"$cluster\"}",
     "legendFormat": "读块时长"
    },
    {
     "expr": "DataNode_WriteBlockOpAvgTime{clusters=~\"$cluster\"}",
     "legendFormat": "写块时长"
    },
    {
     "expr": "DataNode_SentBytes{clusters=~\"$cluster\"}",
     "legendFormat": "数据发送速率"
    },
    {
     "expr": "DataNode_ReceivedBytes{clusters=~\"$cluster\"}",
     "legendFormat": "数据接收速率"
    },
    {
     "expr": "delta(DataNode_DatanodeNetworkErrors{clusters=~\"$cluster\"}[1h])",
     "legendFormat": "网络错误[1h]"
    },
    {
     "expr": "DataNode_ServerActive{clusters=~\"$cluster\"}",
     "legendFormat": "服务状态"
    }
   ]
  }
 ]
}